### ISSUE TITLE
Import Error on macOS

### ISSUE THREAD

**Issue by siosys** [wudingcheng/TSAnalyzer#1]
I'm trying to run TSAnalyzer on a macOS machine and it's throwing up errors. Error code is below. It looks like a compile error with sigseg/libseg1d.so, but shouldn't that library be compiled locally when you run _setup.py install_?

xxxxxx:TSAnalyzer xxxxxx$ TSAnalyzer
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/TSAnalyzer", line 11, in <module>
    load_entry_point('TSAnalyzer==1.2', 'gui_scripts', 'TSAnalyzer')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/TSAnalyzer-1.2-py2.7.egg/TSAnalyzer/__init__.py", line 2, in <module>
    from TSAnalyzer import TSModel
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/TSAnalyzer-1.2-py2.7.egg/TSAnalyzer/TSModel/__init__.py", line 4, in <module>
    from .sigseg import sigseg
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/TSAnalyzer-1.2-py2.7.egg/TSAnalyzer/TSModel/sigseg/__init__.py", line 11, in <module>
    os.path.join(os.path.dirname(__file__), 'libseg1d.so'))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/TSAnalyzer-1.2-py2.7.egg/TSAnalyzer/TSModel/sigseg/libseg1d.so, 6): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/TSAnalyzer-1.2-py2.7.egg/TSAnalyzer/TSModel/sigseg/libseg1d.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/TSAnalyzer-1.2-py2.7.egg/TSAnalyzer/TSModel/sigseg/libseg1d.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

**Comment by wudingcheng** [comment]
Sorry for reply you a bit late.
You can download the packages and compile the ligseg1d, then execute the main.py on your terminal?
